# Generated by Django 2.1.2 on 2018-11-11 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=25833)),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('species', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('genus', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('borough', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('year', models.IntegerField(db_index=True, null=True)),
                ('age', models.IntegerField(db_index=True, null=True)),
                ('circumference', models.IntegerField(db_index=True, null=True)),
                ('height', models.IntegerField(db_index=True, null=True)),
                ('feature_name', models.CharField(db_index=True, max_length=64)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
